"""updated table structure

Revision ID: 3d714ea917fe
Revises: ddbcc3901fd8
Create Date: 2025-05-11 19:40:05.219997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d714ea917fe'
down_revision = 'ddbcc3901fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_visitfrequency', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_table', schema=None) as batch_op:
        batch_op.drop_column('rank_visitfrequency')

    # ### end Alembic commands ###
