"""initial migration

Revision ID: ddbcc3901fd8
Revises: 
Create Date: 2025-05-10 16:11:47.301181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbcc3901fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_table',
    sa.Column('category_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('uwa_email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('profile_path', sa.String(length=255), server_default='static/imgs/Login/Default_user.jfif', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uwa_email')
    )
    op.create_table('relation_requests',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('sender_id', 'receiver_id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_friend_request')
    )
    op.create_table('relationships_Table',
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id_1', 'user_id_2'),
    sa.UniqueConstraint('user_id_1', 'user_id_2', name='uq_friendship')
    )
    op.create_table('spot_table',
    sa.Column('spot_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_name', sa.String(length=50), nullable=True),
    sa.Column('category_ID', sa.Integer(), nullable=True),
    sa.Column('locationx', sa.Float(precision=100), nullable=True),
    sa.Column('locationy', sa.Float(precision=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_ID'], ['category_table.category_ID'], ),
    sa.PrimaryKeyConstraint('spot_ID')
    )
    op.create_table('tendency_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_ID', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_ID'], ['category_table.category_ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_ID', 'snapshot_date', name='uq_category_date')
    )
    with op.batch_alter_table('tendency_table', schema=None) as batch_op:
        batch_op.create_index('idx_category_date', ['category_ID', 'snapshot_date'], unique=False)

    op.create_table('wallpaper_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('collection_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_ID'], ['spot_table.spot_ID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_ID')
    )
    op.create_table('image_table',
    sa.Column('img_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('spot_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_ID'], ['spot_table.spot_ID'], ),
    sa.PrimaryKeyConstraint('img_ID')
    )
    op.create_table('like_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spot_ID'], ['spot_table.spot_ID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'spot_ID')
    )
    op.create_table('reviews_table',
    sa.Column('review_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_ID', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rank_cleanliness', sa.Integer(), nullable=True),
    sa.Column('rank_atmosphere', sa.Integer(), nullable=True),
    sa.Column('rank_comfort', sa.Integer(), nullable=True),
    sa.Column('rank_accessibility', sa.Integer(), nullable=True),
    sa.Column('rank_value', sa.Integer(), nullable=True),
    sa.Column('rank_service_quality', sa.Integer(), nullable=True),
    sa.Column('rank_noise_level', sa.Integer(), nullable=True),
    sa.Column('rank_crowdedness', sa.Integer(), nullable=True),
    sa.Column('rank_overall', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spot_ID'], ['spot_table.spot_ID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('review_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_table')
    op.drop_table('like_table')
    op.drop_table('image_table')
    op.drop_table('collection_table')
    op.drop_table('wallpaper_table')
    with op.batch_alter_table('tendency_table', schema=None) as batch_op:
        batch_op.drop_index('idx_category_date')

    op.drop_table('tendency_table')
    op.drop_table('spot_table')
    op.drop_table('relationships_Table')
    op.drop_table('relation_requests')
    op.drop_table('user_table')
    op.drop_table('category_table')
    # ### end Alembic commands ###
