"""db with spots and caterogires

Revision ID: 8b0da04306a0
Revises: 
Create Date: 2025-05-11 20:19:04.173371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0da04306a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_table',
    sa.Column('category_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spot_table',
    sa.Column('spot_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_name', sa.String(length=50), nullable=True),
    sa.Column('category_ID', sa.Integer(), nullable=True),
    sa.Column('locationx', sa.Float(), nullable=True),
    sa.Column('locationy', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_ID'], ['category_table.category_ID'], name='fk_category_id'),
    sa.PrimaryKeyConstraint('spot_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_table')
    op.drop_table('category_table')
    # ### end Alembic commands ###
