"""added user, image and reviews table

Revision ID: a0d2a026ef47
Revises: 8b0da04306a0
Create Date: 2025-05-11 21:51:44.248828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d2a026ef47'
down_revision = '8b0da04306a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('uwa_email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uwa_email')
    )
    op.create_table('image_table',
    sa.Column('img_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('spot_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_ID'], ['spot_table.spot_ID'], ),
    sa.PrimaryKeyConstraint('img_ID')
    )
    op.create_table('reviews_table',
    sa.Column('review_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_ID', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rank_cleanliness', sa.Integer(), nullable=True),
    sa.Column('rank_atmosphere', sa.Integer(), nullable=True),
    sa.Column('rank_comfort', sa.Integer(), nullable=True),
    sa.Column('rank_accessibility', sa.Integer(), nullable=True),
    sa.Column('rank_value', sa.Integer(), nullable=True),
    sa.Column('rank_service_quality', sa.Integer(), nullable=True),
    sa.Column('rank_noise_level', sa.Integer(), nullable=True),
    sa.Column('rank_crowdedness', sa.Integer(), nullable=True),
    sa.Column('rank_overall', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_ID'], ['spot_table.spot_ID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('review_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_table')
    op.drop_table('image_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
